- name: Debug
  hosts: all
  gather_facts: true
  remote_user: root

  tasks:
    - name : debug
      debug:
        msg: "{{ groups }}"
    - name : debug2
      debug:
        msg: "{{ hostvars.keys() }}"
    - name : debug3
      debug:
        msg: "{{ hostvars[ hostvars.keys() | first ].labels }}"
