apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRESQL_INITSCRIPTS_USERNAME: "postgres"
  # POSTGRESQL_INITSCRIPTS_PASSWORD: loaded as secret (superuser)
  POSTGRESQL_USER: "postgres"
  # POSTGRESQL_PASSWORD: loaded as secret
  POSTGRESQL_DATABASE: "nuisancemaps"
  POSTGRESQL_URL: "jdbc:postgresql://postgresql:5432/nuisancemaps"

---

# this is loaded outside of migration
# because create extension requires superuser privileges, which
# can run on container's initial entrypoint

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb-configmap
data:
  sql: |
    create extension if not exists postgis;
