apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-api
  name: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-api
    spec:
      nodeSelector:
        node.kubernetes.io/class_id: app
      imagePullSecrets:
        - name: regcred
      containers:
        - image: 058264272856.dkr.ecr.us-east-2.amazonaws.com/311crimemap/api:0.0.1-SNAPSHOT
          name: spring-api
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: postgresql-config
          env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRESQL_PASSWORD
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: postgresql-config
                key: POSTGRESQL_URL
          - name: ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: ADMIN_API_KEY
          - name: VITE_MAPTILER_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: VITE_MAPTILER_API_KEY
          - name: GEOAPIFY_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: GEOAPIFY_API_KEY
          - name: FETCH_DATA_DIR
            value: "/data"
          - name: DATA_DIR_MIN_FREE
            value: "5000000000" #5gb
          - name: JAVA_OPTS
            value: "-Dloader.main=com.quirkshop.nuisancemaps.NuisancemapsApplication"
          - name: ASYNC_EXECUTOR_CORE_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_MAX_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_QUEUE_CAPACITY
            value: "8"
          - name: CORS_ORIGINS
            value: "*,http://localhost:5173,http://localhost:4173"
          - name: WORKER_QUERY_LIMIT
            value: "100000"
          - name: BATCH_SIZE
            value: "50000"
          - name: MAX_DATA_RECORDS
            value: "10000"
          ## probes
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["sh", "-c", "sleep 10"]
