apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-api-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - 311crimemap.com
    # NB: tls secret standalone persists without cert manager, issuer containers.
    # once validated secret will be updated and is good.
    #
    secretName: 311crimemap-com-tls
  rules:
    #NB: catches all when no host
    - host: 311crimemap.com
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-api-service
                port:
                  number: 8080
