apiVersion: v1
kind: Service
metadata:
  name: core-db
  namespace: core-db
  annotations:
    description: "alias service for postgresql-ha pgpool service."

spec:
  selector:
    app.kubernetes.io/component: pgpool
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
