apiVersion: v1
kind: ConfigMap
metadata:
  name: pgpool-configmap
data:
  pgpool.conf: |

    # Enable load balancing
    load_balance_mode = on

    # query splitting
    statement_level_load_balance = on

    # backend setup
    backend_port0 = 5432
    backend_weight0 = 1
    backend_flag0 = 'ALLOW_TO_FAILOVER'

    #
    # NOTE: Make sure to scale statefulset to add/remove replica:
    # * kubectl scale statefulset crimemap-db-postgresql-ha-postgresql --replicas=1
    # * make sure primary is gen-0
    #
    # enable/disable replica below:

    backend_port1 = 5432
    backend_weight1 = 1
    backend_flag1 = 'ALLOW_TO_FAILOVER'

    # logs
    log_statement = 'all'
    log_per_node_statement = on
    log_connections = on
    log_hostname = on
