apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-db-postgresql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: manual  # Ensure this matches with the PV
