apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
      app.kubernetes.io/name: postgresql
  serviceName: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
        app.kubernetes.io/name: postgresql
    spec:
      nodeSelector:
        node.kubernetes.io/class_id: db
      # https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift#volumes-in-kubernetes
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      # perms so pgbackrest can write
      initContainers:
      - name: init-container
        image: busybox
        securityContext:
          runAsUser: 0  # Run as root
          privileged: true  # Required to perform privileged actions
        command: ['sh', '-c', 'mkdir -p /backup_db/pgbackrest && chown 1001:1001 /backup-db/pgbackrest']
        volumeMounts:
        - name: backup-db
          mountPath: /backup-db/pgbackrest
      containers:
      - name: postgresql
        image: bitnami/postgresql:16.1.0
        envFrom:
        - configMapRef:
            name: postgresql-config    # defines POSTGRESQL_USER & POSTGRESL_INITSCRIPTS_USERNAME
        - configMapRef:
            name: pgbackrest-config

        env:
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRESQL_PASSWORD
        - name: POSTGRESQL_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRESQL_POSTGRES_PASSWORD
        - name: POSTGRESQL_INITSCRIPTS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secrets
              key: POSTGRESQL_POSTGRES_PASSWORD

        # pgbackrest needed for stanza creation
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pgbackrest-secrets
              key: PGPASSWORD
        - name: PGBACKREST_REPO2_S3_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: pgbackrest-secrets
              key: PGBACKREST_REPO2_S3_KEY_SECRET
        - name: PGBACKREST_REPO2_S3_KEY
          valueFrom:
            secretKeyRef:
              name: pgbackrest-secrets
              key: PGBACKREST_REPO2_S3_KEY

        ports:
          # can't use configMap on ports
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - name: data-db
          mountPath: /bitnami/postgresql

        - name: backup-db
          mountPath: /backup_db/pgbackrest

        - name: dshm # shared memory
          mountPath: /dev/shm

        - name: initdb
          mountPath: /docker-entrypoint-initdb.d/01_enable_postgis.sql
          subPath: 01_enable_postgis.sql

        - name: pgbackrest-configmap-volume
          mountPath: /etc/pgbackrest.conf
          subPath: pgbackrest.conf   # specifies file in configMap

        - name: pgbackrest-configmap-volume
          mountPath: /opt/bitnami/postgresql/conf/conf.d/archive.conf
          subPath: archive.conf

        - name: postgresql-configmap-volume
          mountPath: /opt/bitnami/postgresql/conf/conf.d/custom_postgresql.conf
          subPath: custom_postgresql.conf

      volumes:

      - name: backup-db         #local host db backup
        hostPath:
          path: /backup_db/pgbackrest
          type: DirectoryOrCreate

      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi # NB: Gibibyte -> 1 GiB = 1,073,741,824 bytes

      - name: initdb
        configMap:
          name: postgresql-initdb-configmap
          items:
            - key: sql
              path: 01_enable_postgis.sql

      - name: postgresql-configmap-volume
        configMap:
          name: postgresql-config

      - name: pgbackrest-configmap-volume
        configMap:
          name: pgbackrest-config

  volumeClaimTemplates:
  - metadata:
      name: data-db
    spec:
      # NB: creates a pvc
      storageClassName: hcloud-volumes
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 64Gi
