apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-13f75af3-fc2e-403c-bc22-9a11ab3d550b
spec:
  capacity:
    storage: 128Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  csi:
    driver: csi.hetzner.cloud
    volumeHandle: "101298497"    # Replace with the actual ID (not name)

    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node.kubernetes.io/class_id
          operator: In
          values:
          - db
