version: '3.4'
services:
  # these are currently setup as "dev" first.
  # Will need to build standalone executable containers.
  web:
    image: 'vergeman/nuisancemaps/web'
    build: "./web"
    volumes:
      - ./web:/web
    command: bash -c "npm run dev"
    ports:
      - 5173:5173  # dev server
      - 4173:4173  # prod build preview

  api:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./api:/api
      - $HOME/.m2:/root/.m2
    working_dir: '/api'
    command: ash -c "./mvnw spring-boot:run -Dstart-class=com.quirkshop.nuisancemaps.NuisancemapsApplication"
    ports:
      - 8080:8080
    env_file:
      - .env.dev

  worker:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./api:/api
      - $HOME/.m2:/root/.m2
    working_dir: '/api'
    command: ash -c "./mvnw spring-boot:run -Dstart-class=com.quirkshop.nuisancemaps.WorkerApplication"
    env_file:
      - .env.dev
    # deploy: # to test multiple workers
    #   replicas: 3

  db:
    image: 'bitnami/postgresql:16.1.0'
    volumes:
      - nuisancemaps_db:/bitnami/postgresql
      # installed at "per database" level
      - ./db/01_enable_postgis.sql:/docker-entrypoint-initdb.d/01_enable_postgis.sql
    #network_mode: "host"
    ports:
      - 5432:5432
    env_file:
      - .env.dev

volumes:
  nuisancemaps_db:
