version: '3.4'
services:
  # these are currently setup as "dev" first.
  # Will need to build standalone executable containers.
  web:
    image: 'vergeman/nuisancemaps/web'
    build: "./web"
    volumes:
      - ./web:/web
    command: bash -c "npm run dev"
    ports:
      - 5173:5173

  api:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./api:/api
      - $HOME/.m2:/root/.m2
    working_dir: '/api'
    command: bash -c "./mvnw spring-boot:run -Dstart-class=com.quirkshop.nuisancemaps.NuisancemapsApplication"
    ports:
      - 8080:8080
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=db_example

  worker:
    image: eclipse-temurin:17-jdk-alpine
    volumes:
      - ./api:/api
      - $HOME/.m2:/root/.m2
    working_dir: '/api'
    command: bash -c "./mvnw spring-boot:run -Dstart-class=com.quirkshop.nuisancemaps.WorkerApplication"
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=db_example

  db:
    image: 'bitnami/postgresql:16.1.0'
    volumes:
      # installed at "per database" level
      - ./db/01_enable_postgis.sql:/docker-entrypoint-initdb.d/01_enable_postgis.sql
    #network_mode: "host"
    ports:
      - 5432:5432
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=db_example
