apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-worker
  name: spring-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-worker
    spec:
      affinity:
        nodeAffinity:
          # Hard requirement: Avoid `node.kubernetes.io/class_id=cntrl`
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: NotIn
                    values:
                      - cntrl
          # Preference: Prefer `node.kubernetes.io/class_id=worker`
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: In
                    values:
                      - worker
            # Lower priority preference for `node.kubernetes.io/class_id=app`
            - weight: 50
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/class_id
                    operator: In
                    values:
                      - app
            # Lower priority preference for `node.kubernetes.io/class_instance=gen-0`
            - weight: 10
              preference:
                matchExpressions:
                  - key: node.kubernetes.io/class_instance
                    operator: In
                    values:
                      - gen-0
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${IMAGE_REPO}/311crimemap/api:0.0.1-SNAPSHOT
          name: spring-worker
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1400Mi"
            limits:
              memory: "3200Mi"
          envFrom:
          - configMapRef:
              name: postgresql-configmap
          env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRESQL_PASSWORD
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: POSTGRESQL_URL
          - name: VITE_MAPTILER_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: VITE_MAPTILER_API_KEY
          - name: GEOAPIFY_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: GEOAPIFY_API_KEY
          - name: FETCH_DATA_DIR
            value: "/data"
          - name: DATA_DIR_MIN_FREE
            value: "5000000000" #5gb
          - name: JAVA_OPTS
            value: "-Dloader.main=com.quirkshop.nuisancemaps.WorkerApplication"
          - name: JAVA_TOOL_OPTS
            value: "Xms512m -Xmx3000m"
          - name: ASYNC_EXECUTOR_CORE_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_MAX_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_QUEUE_CAPACITY
            value: "8"
          - name: WORKER_QUERY_LIMIT
            value: "100000"
          - name: BATCH_SIZE
            value: "50000"
          - name: VITE_MAX_DATA_RECORDS
            value: "20000"
          - name: MAPTILER_HOST_REFERER
            value: "api.311crimemap.com"

          volumeMounts:
            - name: data-volume
              mountPath: /data

      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-pvc

          # # probes
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["sh", "-c", "sleep 10"]
