apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-worker
  name: spring-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-worker
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: 058264272856.dkr.ecr.us-east-2.amazonaws.com/311crimemap/api:0.0.1-SNAPSHOT
          name: spring-worker
          envFrom:
          - configMapRef:
              name: postgresql-config
          env:
          - name: POSTGRESQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRESQL_PASSWORD
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: postgresql-config
                key: POSTGRESQL_URL
          - name: JAVA_OPTS
            value: "-Dloader.main=com.quirkshop.nuisancemaps.WorkerApplication"
          - name: ASYNC_EXECUTOR_CORE_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_MAX_POOL_SIZE
            value: "4"
          - name: ASYNC_EXECUTOR_QUEUE_CAPACITY
            value: "8"
          - name: WORKER_QUERY_LIMIT
            value: "100000"

          # # probes
          # livenessProbe:
          #   httpGet:
          #     path: /actuator/health/liveness
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /actuator/health/readiness
          #     port: 8080
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["sh", "-c", "sleep 10"]
