apiVersion: v1
kind: Pod
metadata:
  name: pg-debug
  namespace: core-db
spec:
  containers:
  - name: pg-debug
    image: bitnamilegacy/postgresql:16.4.0
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data
      mountPath: /bitnami/postgresql
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-core-db-postgresql-ha-postgresql-0
