apiVersion: batch/v1
kind: Job
metadata:
  name: pgbackrest-db-restore
spec:
  template:
    spec:
      # https://docs.bitnami.com/tutorials/running-non-root-containers-on-openshift#volumes-in-kubernetes
      securityContext:
        runAsUser: 1001
        fsGroup: 1001

      containers:
      - name: postgresql
        image: bitnami/postgresql:16.1.0
        command: ["bin/bash", "-c"]
        args:
          - |
            pgbackrest --stanza=311crimemap --repo=2 --delta \
             --log-level-console=detail restore

        envFrom:
          - configMapRef:
              name: postgresql-configmap
          - configMapRef:
              name: pgbackrest-configmap

        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgbackrest-secrets
                key: PGPASSWORD

          - name: PGBACKREST_REPO2_S3_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: pgbackrest-secrets
                key: PGBACKREST_REPO2_S3_KEY_SECRET

          - name: PGBACKREST_REPO2_S3_KEY
            valueFrom:
              secretKeyRef:
                name: pgbackrest-secrets
                key: PGBACKREST_REPO2_S3_KEY

        volumeMounts:
          - name: postgresql-data
            mountPath: /bitnami/postgresql

          - name: pgbackrest-configmap-volume
            mountPath: /etc/pgbackrest.conf
            subPath: pgbackrest.conf   # specifies file in configMap

          - name: pgbackrest-configmap-volume
            mountPath: /opt/bitnami/postgresql/conf/conf.d/archive.conf
            subPath: archive.conf

      volumes:
        - name: postgresql-data
          # NB: helm auto-generates the claimName:
          # "data" - helm project - image container - statefulset - ordinal
          persistentVolumeClaim:
            claimName: data-crimemap-db-postgresql-ha-postgresql-0

        - name: pgbackrest-configmap-volume
          configMap:
            name: pgbackrest-configmap

      restartPolicy: Never
  backoffLimit: 4
