apiVersion: batch/v1
kind: Job
metadata:
  name: spring-liquibase-migration
  namespace: crimemap
spec:
  template:
    spec:
      containers:
      - name: spring-liquibase-migration
        image: liquibase/liquibase:4.25
        # override docker based host url to access headless service
        # NB: host address requires postgres-service enabled
        command: ["liquibase", "update"]
        envFrom:
          - configMapRef:
              name: postgresql-configmap
        env:
          - name: LIQUIBASE_COMMAND_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: POSTGRESQL_USER
          - name: LIQUIBASE_COMMAND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secrets
                key: POSTGRESQL_PASSWORD
          - name: LIQUIBASE_COMMAND_URL
            valueFrom:
              configMapKeyRef:
                name: postgresql-configmap
                key: POSTGRESQL_URL

        volumeMounts:

          - name: liquibase-properties
            mountPath: /liquibase/liquibase.properties
            subPath: liquibase.properties

          - name: liquibase-changelog-master
            mountPath: /liquibase/db/changelog-master.yml
            subPath: changelog-master.yml

          - name: liquibase-changelogs
            mountPath: /liquibase/db/changelogs/
      #
      # see ./create-configmaps.sh
      #
      volumes:

      - name: liquibase-properties
        configMap:
          name: liquibase-properties-configmap

      - name: liquibase-changelog-master
        configMap:
          name: liquibase-changelog-master-configmap

      - name: liquibase-changelogs
        configMap:
          name: liquibase-changelogs-configmap

      restartPolicy: Never
  backoffLimit: 4
