apiVersion: v1
kind: ConfigMap
metadata:
  name: init-postgresql-configmap
data:
  01-create-extensions.sql: |
    create extension if not exists postgis;
    create extension if not exists btree_gist;

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  POSTGRESQL_USER: "postgres"
  POSTGRESQL_URL: "jdbc:postgresql://db:5432/nuisancemaps"

  custom_postgresql.conf: |
    # custom_postgresql.conf
    shared_buffers = 2GB
    work_mem = 64MB
    maintenance_work_mem = 512MB
    max_wal_size = 2GB
    max_connections = 160
    # autovacuum = off # disable for import
