apiVersion: v1
kind: ConfigMap
metadata:
  name: pgbackrest-configmap
  namespace: core-db
data:
  PGBACKREST_STANZA: "${PGBACKREST_STANZA}"
  pgbackrest.conf: |
    [global]
    log-level-console=info
    start-fast=y
    log-level-file=warn

    [global:archive-get]
    process-max=2

    [global:archive-push]
    process-max=2

    [${PGBACKREST_STANZA}]
    pg1-user=postgres
    pg1-path=/bitnami/postgresql/data
    pg1-database=postgres # default database to connect to (not backup)
    # log-path=/backup_db/pgbackrest

    # "local" backup
    # repo1-path=/backup_db/pgbackrest
    # repo1-retention-full=2

    # s3 bucket backup
    repo2-type=s3
    repo2-s3-region=${PGBACKREST_REPO2_S3_REGION}
    repo2-s3-endpoint=${PGBACKREST_REPO2_S3_ENDPOINT}
    repo2-s3-bucket=${PGBACKREST_REPO2_S3_BUCKET}
    repo2-retention-diff=2
    repo2-retention-full=2

    # creds are set in respective .env.*
    # note prefix and underscore: PGBACKREST_REPO2_S3_KEY
    #repo2-s3-key=accessKey1
    #repo2-s3-key-secret=verySecretKey1

  archive.conf: |
    archive_mode = on
    archive_command = 'pgbackrest --stanza=${PGBACKREST_STANZA} archive-push %p'

  run.sh: |
    #!/bin/bash
    # override docker container run.sh
    #
    # pg_restore: need to add recovery.signal for restore, container
    # automatically removes it
    # only needed to override for restore operation

    # shellcheck disable=SC1091

    set -o errexit
    set -o nounset
    set -o pipefail
    # set -o xtrace # Uncomment this line for debugging purpose

    # Load libraries
    . /opt/bitnami/scripts/libpostgresql.sh
    . /opt/bitnami/scripts/libos.sh

    # Load PostgreSQL environment variables
    . /opt/bitnami/scripts/postgresql-env.sh

    #
    # RECOVERY.SIGNAL ADDITION
    #
    touch /bitnami/postgresql/data/recovery.signal

    flags=("-D" "$POSTGRESQL_DATA_DIR" "--config-file=$POSTGRESQL_CONF_FILE" "--external_pid_file=$POSTGRESQL_PID_FILE" "--hba_file=$POSTGRESQL_PGHBA_FILE")
    cmd=$(command -v postgres)

    info "** Starting PostgreSQL **"
    if am_i_root; then
         exec gosu "$POSTGRESQL_DAEMON_USER" "$cmd" "${flags[@]}"
    else
         exec "$cmd" "${flags[@]}"
    fi

