spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USER}
spring.datasource.password=${POSTGRESQL_PASSWORD}

spring.jpa.properties.hibernate.jdbc.batch_size=${BATCH_SIZE}
spring.jpa.properties.hibernate.order_inserts = true
spring.jpa.properties.hibernate.order_updates = true

spring.liquibase.enabled=false
# can be single file or directory
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yml


spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=<create | create-drop | update | validate | none>
#create – on start, Hibernate first drops existing tables, then creates new tables
#update – the object model created based on the mappings (annotations or XML) is compared with the existing schema, and then Hibernate updates the schema according to the diff. It never deletes the existing tables or columns even if they are no more required by the application
#create-drop – similar to create, with the addition that Hibernate will drop the database after all operations are completed. Typically used for unit testing
#validate – Hibernate only validates whether the tables and columns exist, otherwise it throws an exception
#none - typically used in prod, don't manage

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.minimumIdle=10

app.scheduling.enabled=true

#
# actuator / prometheus
#
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always