driver: org.postgresql.Driver
url: jdbc:postgresql://db:5432/db_example

#
# can't use env variables here (crippleware'd)
# can use env variables via command line:
#./mvnw liquibase:update -Dusername=$POSTGRESQL_USER -Dpassword=$POSTGRESQL_PASSWORD
#
username: postgres
password: admin

# changeLogFile: migrations directory applied to database above
changeLogFile: db/changelog-master.yml

#
# liquibase - hibernate
#
# referenceURL: instructs liquibase to use hibernate JPA as the source schema
# referenceDriver: driver for referenceURL
#
# target schema is url above (postgres)
# when generating a diff, liquibase compares ORM JPA via referenceURL schema
# against schema of url above (postgresql)
#
#./mvnw liquibase:diff
#
referenceUrl=hibernate:spring:com.quirkshop.nuisancemaps?dialect=org.hibernate.dialect.PostgreSQLDialect\
    &hibernate.physical_naming_strategy=com.quirkshop.nuisancemaps.config.SnakeCaseNamingStrategy
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver


# diffChangeLogFile: output file collects diffs for change
# This needs to be verified: issues with table name capitalization; lack of default values, etc.
# But it's a good start.
diffChangeLogFile: src/main/resources/db/changelogs/generated_changelog.sql

#contexts