# -*- coding: utf-8 -*-
"""CrimeClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVxnSvdSxNVyqEY1e5s9Nkupa3bL87Cf
"""
# to run in docker:
# python set_fit_crime.py / set_fit_load.py
#
# in colab or aws:
# !pip install torch==2.2.1 transformers==4.38.2 scikit-learn evaluate accelerate datasets setfit

from setfit import SetFitModel, Trainer, TrainingArguments, sample_dataset
from datasets import load_dataset, Dataset
import pandas as pd
import json

candidate_labels = [
    "Violent",
    "Property",
    "Theft",
    "Fraud / Forgery",
    "Vice Drugs Weapon",
    "Public Order",
    "Other"
]

#
# example data format:
# all_data = [ { "text": "crime", "label": 6}, ...]
#
#
json_file = open("./data/train.json")
all_data = json.load(json_file)

# Initializing a new SetFit model
m = "BAAI/bge-small-en-v1.5"
#m = "sentence-transformers/all-MiniLM-L6-v2"

dir = "setfit-bge-small-v1.5-sst2-8-shot"

model = SetFitModel.from_pretrained(m, labels=candidate_labels)

# Preparing the dataset

datasets = Dataset.from_list(all_data).shuffle(seed=42)\
                  .class_encode_column("label")\
                  .train_test_split(test_size=0.125, stratify_by_column="label")

print( len(datasets['train']))
print( len(datasets['test']))

# replaced by stratify_by_column
# train_dataset = sample_dataset(datasets['train'], label_column="label", num_samples=12)
# test_dataset = sample_dataset(datasets['test'], label_column="label", num_samples=12)

train_dataset = datasets['train']
test_dataset = datasets['test']
print(test_dataset[0])

# Preparing the training arguments
args = TrainingArguments(
    batch_size=32,
    num_epochs=7,
)

# Preparing the trainer
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
)
trainer.train()
exit()

# Evaluating
metrics = trainer.evaluate(test_dataset)
print(metrics)
# => {'accuracy': 0.8511806699615596}

# Saving the trained model
model.save_pretrained(dir)
# or
# model.push_to_hub("tomaarsen/setfit-bge-small-v1.5-sst2-8-shot")

# Loading a trained model
#model = SetFitModel.from_pretrained("tomaarsen/setfit-bge-small-v1.5-sst2-8-shot") # Load from the Hugging Face Hub
# or
#model = SetFitModel.from_pretrained("setfit-bge-small-v1.5-sst2-8-shot") # Load from a local directory

# sanity check inference
preds = model.predict([
    "ASSAULT 3 & RELATED OFFENSES",
    "BURGLARY",
    "CANNABIS RELATED OFFENSES",
    "CHILD ABANDONMENT/NON SUPPORT"
])

print(preds)

# to be loaded via set_fit_load.py
# destination (archive name), type, archive directory source
from shutil import make_archive
make_archive(f"models/{dir}", 'zip', dir)
