apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    app.kubernetes.io/name: postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
  clusterIP: None # headless (creates DNS record per pod)
  selector:
    app: postgresql
