-- liquibase formatted sql
-- changeset root:1705618434477-1
CREATE SEQUENCE IF NOT EXISTS data_crime_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1705618434477-2
CREATE SEQUENCE IF NOT EXISTS source_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1705618434477-3
CREATE TABLE source (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category VARCHAR(255),
    description VARCHAR(255),
    url VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT "sourcePK" PRIMARY KEY (id)
);

-- changeset root:1705618434477-4
CREATE TABLE data_crime (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id INTEGER REFERENCES source(id),
    report_num INTEGER,
    category VARCHAR(255),
    description VARCHAR(255),
    location VARCHAR(255),
    latitude FLOAT(53) NOT NULL,
    longitude FLOAT(53) NOT NULL,
    point GEOMETRY,
    reported_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,

    CONSTRAINT "data_crimePK" PRIMARY KEY (id),
    CONSTRAINT fk_source FOREIGN KEY (source_id) REFERENCES source(id)
);

