-- liquibase formatted sql
-- changeset root:1706119904997-1
CREATE SEQUENCE IF NOT EXISTS data_job_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1706119904997-2
CREATE TABLE data_job (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id INTEGER REFERENCES source(id) NOT NULL,
    status VARCHAR(255),
    url VARCHAR(255),
    param_limit INTEGER NOT NULL,
    param_offset INTEGER NOT NULL,
    order_key VARCHAR(255),
    num_results INTEGER,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT "data_jobPK" PRIMARY KEY (id)
);