-- liquibase formatted sql
-- changeset root:1706200248319-1
CREATE SEQUENCE IF NOT EXISTS data_311_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1706200248319-2
CREATE TABLE data_311 (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_id INTEGER REFERENCES source (id) NOT NULL,
    report_num VARCHAR(255),
    category VARCHAR(255),
    description VARCHAR(255),
    location VARCHAR(255),
    latitude FLOAT(53) NOT NULL,
    longitude FLOAT(53) NOT NULL,
    point GEOMETRY,
    reported_at TIMESTAMP(6) WITHOUT TIME ZONE,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT "data_311PK" PRIMARY KEY (id)
);
