-- liquibase formatted sql

-- changeset root:1706488888974-1
ALTER TABLE data_crime
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN latitude DROP NOT NULL,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude DROP NOT NULL;

-- changeset root:1706488888974-2
ALTER TABLE data_311
ALTER COLUMN latitude TYPE DOUBLE PRECISION,
ALTER COLUMN latitude DROP NOT NULL,
ALTER COLUMN longitude TYPE DOUBLE PRECISION,
ALTER COLUMN longitude DROP NOT NULL;
