-- liquibase formatted sql

-- changeset root:1706642920511-1
CREATE SEQUENCE IF NOT EXISTS data_error_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1706642920511-2
CREATE TABLE data_error (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_job_id INTEGER REFERENCES data_job(id),
    content VARCHAR(255),
    error_msg VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,    
    CONSTRAINT "data_errorPK" PRIMARY KEY (id)
);
