-- liquibase formatted sql

-- changeset root:1711917100084-1
CREATE SEQUENCE IF NOT EXISTS category_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1711917100084-2

CREATE TABLE category (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_type VARCHAR(255),
  text VARCHAR(255),
  label INTEGER,
  parent_id INTEGER REFERENCES category(id),
  created_at TIMESTAMP(6) WITHOUT TIME ZONE,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
  CONSTRAINT "categoryPK" PRIMARY KEY (id)
);

