-- liquibase formatted sql

-- changeset root:1712264255976-1
CREATE SEQUENCE IF NOT EXISTS text_category_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1712264255976-2
CREATE TABLE text_category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data_type VARCHAR(255),
    text VARCHAR(255),
    category_id INTEGER REFERENCES category (id) NOT NULL,
    created_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
    CONSTRAINT "text_categoryPK" PRIMARY KEY (id)
);

-- changeset root:1712264255976-3
ALTER TABLE text_category
    ADD CONSTRAINT "UniqueDataTypeAndTextAndLabel" UNIQUE (data_type, text, category_id);

-- changeset root:1712264255976-4
CREATE INDEX idx_data_type_text_category
    ON text_category (data_type);
