-- liquibase formatted sql

-- changeset root:1712534468423-1
CREATE SEQUENCE IF NOT EXISTS mapping_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1712534468423-2
CREATE TABLE mapping (
    id
        INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description
        VARCHAR(255),
    latitude
        VARCHAR(255),
    location
        VARCHAR(255),
    longitude
        VARCHAR(255),
    report_category
        VARCHAR(255),
    report_num
        VARCHAR(255),
    reported_at
        VARCHAR(255),
    reported_at2
        VARCHAR(255),
    created_at
        TIMESTAMP(6),
    updated_at
        TIMESTAMP(6),
    CONSTRAINT "mappingPK" PRIMARY KEY (id)
);

-- changeset root:1712534468423-3
-- TODO: set to NOT NULL after migration
ALTER TABLE source ADD COLUMN mapping_id INT8;

-- changeset root:1712534468423-4
ALTER TABLE source
    ADD COLUMN source_config_notes VARCHAR(255);

-- changeset root:1712534468423-5
-- enforce 1 to 1 relation
ALTER TABLE source
    ADD CONSTRAINT uc_sourcemapping_id_col UNIQUE (mapping_id);

-- changeset root:1712534468423-6
ALTER TABLE source
    ADD CONSTRAINT "source_mapping_id_fkey" FOREIGN KEY (mapping_id) REFERENCES mapping (id);
