-- liquibase formatted sql

-- changeset root:1721943481030-1
CREATE SEQUENCE  IF NOT EXISTS locale_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1721943481030-2

CREATE TABLE locale (id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                     CONSTRAINT "localePK" PRIMARY KEY (id),
                     name VARCHAR(255),
                     description VARCHAR(255),
                     icon_name VARCHAR(255),
                     icon_unicode VARCHAR(255),
                     location GEOMETRY,
                     created_at TIMESTAMP(6) WITHOUT TIME ZONE,
                     updated_at TIMESTAMP(6) WITHOUT TIME ZONE);

-- changeset root:1721943481030-3
ALTER TABLE source
  ADD COLUMN locale_id INT8;

-- changeset root:1721943481030-4
ALTER TABLE source
  ADD CONSTRAINT "source_locale_id_fkey" FOREIGN KEY (locale_id) REFERENCES locale (id);
