-- liquibase formatted sql

-- changeset root:1724280940340-1
CREATE SEQUENCE IF NOT EXISTS geocode_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1724280940340-2
CREATE TABLE geocode (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  source_id INTEGER REFERENCES source(id) NOT NULL,
  address VARCHAR(512),
  latitude FLOAT(53),
  longitude FLOAT(53),
  created_at TIMESTAMP(6) WITHOUT TIME ZONE,
  updated_at TIMESTAMP(6) WITHOUT TIME ZONE,
  CONSTRAINT "geocodePK" PRIMARY KEY (id)
);


