-- liquibase formatted sql

-- changeset root:1724884338206-1
CREATE SEQUENCE IF NOT EXISTS pending_text_category_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1724884338206-2

CREATE TABLE pending_text_category (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  data_job_id INTEGER REFERENCES data_job(id) NOT NULL,
  data_type VARCHAR(255),
  text VARCHAR(255),
  CONSTRAINT "pending_text_categoryPK" PRIMARY KEY (id));

-- changeset root:1724884338206-3
ALTER TABLE pending_text_category ADD CONSTRAINT "PendingTextCategory_UniqueDataTypeAndText" UNIQUE (data_type, text);

