-- liquibase formatted sql

-- changeset root:1732308179195-1
CREATE SEQUENCE IF NOT EXISTS data_url_cache_seq START WITH 1 INCREMENT BY 1;

-- changeset root:1732308179195-2
CREATE TABLE data_url_cache (
    id
        INT8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    count
        INT8 NOT NULL,
    hash_code
        VARCHAR(255) NOT NULL,
    url
        VARCHAR(255) NOT NULL,
    CONSTRAINT "data_url_cachePK" PRIMARY KEY (id)
);

-- changeset root:1732308179195-3
ALTER TABLE data_url_cache
    ADD CONSTRAINT uc_data_url_cachehash_code_col UNIQUE (hash_code);

-- changeset root:1732308179195-4
ALTER TABLE data_url_cache
    ADD CONSTRAINT uc_data_url_cacheurl_col UNIQUE (url);
