
package com.quirkshop.nuisancemaps.service.parserstrategy;

public enum ParserStrategy {
    /* austin */
    STREET_NAME_ERSI_AUSTIN,
    OCCURRENCE_DATE_ERSI_AUSTIN,
    CREATED_DATE_CSV_AUSTIN,
    REPORTED_AT_CSV_AUSTIN,
    REPORTED_AT2_CSV_AUSTIN,

    /* dallas 311 */
    LATITUDE_311_DALLAS,
    LONGITUDE_311_DALLAS,
    LATITUDE_CSV_311_DALLAS,
    LONGITUDE_CSV_311_DALLAS,
    REPORTED_AT_CSV_311_DALLAS,

    /* dallas crime */
    LATITUDE_CSV_CRIME_DALLAS,
    LONGITUDE_CSV_CRIME_DALLAS,
    REPORTED_AT_CRIME_DALLAS,
    REPORTED_AT2_CRIME_DALLAS,
    REPORTED_AT_CSV_CRIME_DALLAS,
    REPORTED_AT2_CSV_CRIME_DALLAS,

    /* chicago */
    REPORTED_AT_CSV_CRIME_CHICAGO,
    REPORTED_AT_CSV_311_CHICAGO,

    /* san francisco */
    REPORTED_AT_CSV_CRIME_SAN_FRANCISCO,
    REPORTED_AT_CSV_311_SAN_FRANCISCO,

    /* new york city */
    REPORTED_AT_CSV_CRIME_NEW_YORK_CITY,
    REPORTED_AT2_CSV_CRIME_NEW_YORK_CITY,
    REPORTED_AT_CSV_311_NEW_YORK_CITY,

    /* boston */
    REPORTED_AT_CSV_CRIME_TIMEZONE_OFFSET_BOSTON,
    REPORTED_AT_CSV_CRIME_BOSTON,
    REPORTED_AT_CSV_311_BOSTON,

    /* los angeles */
    REPORTED_AT_CSV_CRIME_LA,
    REPORTED_AT2_CSV_CRIME_LA,
    REPORTED_AT_311_LA,
    REPORTED_AT_CSV_311_LA,

    /* houston */
    REPORTED_AT_CSV_311_HOUSTON,
    REPORTED_AT_CSV2_311_HOUSTON,
    REPORTED_AT_XLS_CRIME_HOUSTON,
    ADDRESS_XLS_CRIME_HOUSTON,

    /* philadelphia */
    REPORTED_AT_CSV_CRIME_PHILADELPHIA,
    REPORTED_AT_CSV_311_PHILADELPHIA,

    /* san diego */
    REPORTED_AT_CSV_CRIME_SAN_DIEGO,

    /* charlotte */
    ADDRESS_CSV_CRIME_CHARLOTTE,
    REPORTED_AT_CSV_CRIME_CHARLOTTE,
    REPORTED_AT_CSV_311_CHARLOTTE,

    /* denver */
    REPORTED_AT_CSV_CRIME_DENVER,
    REPORTED_AT_CSV_311_DENVER,

    /* detroit */
    REPORTED_AT_CSV_CRIME_DETROIT,
    REPORTED_AT_CSV_311_DETROIT,

    /* memphis */
    REPORTED_AT_CSV_CRIME_MEMPHIS,
    REPORTED_AT_CSV_311_MEMPHIS,
    LATITIUDE_CSV_311_MEMPHIS,
    LONGITUDE_CSV_311_MEMPHIS

}

