global:
  nodeSelector:
    node.kubernetes.io/class_id: cntrl

# Explicitly set nodeSelector for subchart components may not inherit global

alertmanager:
  alertmanagerSpec:
    affinity:
      nodeAffinity:
        # Preference: Prefer `node.kubernetes.io/class_id=cntrl`
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: In
                  values:
                    - cntrl
          # Lower priority preference for `node.kubernetes.io/class_id=gen`
          - weight: 10
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: In
                  values:
                    - gen

#works
prometheusOperator:
  affinity:
    nodeAffinity:
      # Preference: Prefer `node.kubernetes.io/class_id=cntrl`
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - cntrl
        # Lower priority preference for `node.kubernetes.io/class_id=gen`
        - weight: 10
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - gen

prometheus:
  prometheusSpec:
    serviceMonitorNamespaceSelector:
      matchLabels: {}  # watch all namespaces
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    affinity:
      nodeAffinity:
        # Preference: Prefer `node.kubernetes.io/class_id=cntrl`
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: In
                  values:
                    - cntrl
          # Lower priority preference for `node.kubernetes.io/class_id=gen`
          - weight: 10
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: In
                  values:
                    - gen

#work
grafana:
  affinity:
    nodeAffinity:
      # Preference: Prefer `node.kubernetes.io/class_id=cntrl`
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - cntrl
        # Lower priority preference for `node.kubernetes.io/class_id=gen
        - weight: 10
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - gen

# works
kube-state-metrics:
  affinity:
    nodeAffinity:
      # Preference: Prefer `node.kubernetes.io/class_id=cntrl`
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - cntrl
        # Lower priority preference for `node.kubernetes.io/class_id=gen`
        - weight: 10
          preference:
            matchExpressions:
              - key: node.kubernetes.io/class_id
                operator: In
                values:
                  - gen
