# Enable load balancing
load_balance_mode = on

# query splitting
statement_level_load_balance = on

# backend nodes
backend_hostname0 = 'pg-0'
backend_port0 = 5432
backend_weight0 = 0
backend_flag0 = 'ALLOW_TO_FAILOVER'

# backend_hostname1 = 'pg-1'
# backend_port1 = 5432
# backend_weight1 = 1
# backend_flag1 = 'ALLOW_TO_FAILOVER'

log_statement = 'none'
log_min_messages = 'warning'
log_per_node_statement = off
log_connections = on
log_hostname = on
