[global]
log-level-console=info
start-fast=y
log-level-file=warn

[311crimemap]
pg1-user=postgres
pg1-path=/bitnami/postgresql/data
pg1-database=nuisancemaps
log-path=/mnt/pgbackrest

# local backup volume mount (see docker-compose.yml)
# docker config: './db' host directory mounted container at '/mnt'
repo1-path=/mnt/pgbackrest
repo1-retention-full=2

# s3 bucket backup
repo2-type=s3
repo2-s3-region=us-east-2
repo2-s3-endpoint=s3.us-east-2.amazonaws.com
repo2-s3-bucket=311crimemap-dev-db
repo2-retention-full=2

# creds are set in respective .env.*
# note prefix and underscore: PGBACKREST_REPO2_S3_KEY
#repo2-s3-key=accessKey1
#repo2-s3-key-secret=verySecretKey1
