apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    affinity:
      nodeAffinity:
        # Hard requirement: Avoid `node.kubernetes.io/class_id=cntrl`
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: NotIn
                  values:
                    - cntrl
        preferredDuringSchedulingIgnoredDuringExecution:
          # Preference: Prefer `node.kubernetes.io/class_id=app`
          - weight: 100
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_id
                  operator: In
                  values:
                    - app
          # Lower priority preference for `node.kubernetes.io/class_instance=gen-0`
          - weight: 10
            preference:
              matchExpressions:
                - key: node.kubernetes.io/class_instance
                  operator: In
                  values:
                    - gen-0
