
package com.quirkshop.nuisancemaps.config;

public enum ParserStrategy {
    LATITUDE_311_DALLAS,
    LONGITUDE_311_DALLAS,
    REPORTEDAT_CRIME_DALLAS,
    REPORTEDAT2_CRIME_DALLAS,
    REPORTEDAT_CRIME_NEWYORKCITY,
    CREATED_DATE_311_NEWYORKCITY,
    REPORTEDAT_BOSTON,
    REPORTEDAT_BOSTON_TIMEZONE_OFFSET
}
