
package com.quirkshop.nuisancemaps.config;

public enum ParserStrategy {
    /* austin */
    STREET_NAME_ERSI_AUSTIN,
    OCCURRENCE_DATE_ERSI_AUSTIN,
    CREATED_DATE_CSV_AUSTIN,
    REPORTED_AT_CSV_AUSTIN,
    REPORTED_AT2_CSV_AUSTIN,

    /* dallas 311 */
    LATITUDE_311_DALLAS,
    LONGITUDE_311_DALLAS,
    LATITUDE_CSV_311_DALLAS,
    LONGITUDE_CSV_311_DALLAS,
    REPORTED_AT_CSV_311_DALLAS,

    /* dallas crime */
    LATITUDE_CSV_CRIME_DALLAS,
    LONGITUDE_CSV_CRIME_DALLAS,
    REPORTEDAT_CRIME_DALLAS,
    REPORTEDAT2_CRIME_DALLAS,
    REPORTEDAT_CSV_CRIME_DALLAS,
    REPORTEDAT2_CSV_CRIME_DALLAS,

    /* chicago */
    REPORTED_AT_CSV_CRIME_CHICAGO,
    REPORTED_AT_CSV_311_CHICAGO,

    /* san francisco */
    REPORTED_AT_CSV_CRIME_SAN_FRANCISCO,
    REPORTED_AT_CSV_311_SAN_FRANCISCO,

    /* new york city */
    REPORTED_AT_CSV_CRIME_NEW_YORK_CITY,
    REPORTED_AT2_CSV_CRIME_NEW_YORK_CITY,
    REPORTED_AT_CSV_311_NEW_YORK_CITY,

    /* boston */
    REPORTED_AT_CSV_CRIME_TIMEZONE_OFFSET_BOSTON,
    REPORTED_AT_CSV_CRIME_BOSTON,
    REPORTED_AT_CSV_311_BOSTON

}
