
package com.quirkshop.nuisancemaps.config;

public enum ParserStrategy {
    /* austin */
    STREET_NAME_ERSI_AUSTIN,
    OCCURRENCE_DATE_ERSI_AUSTIN,
    CREATED_DATE_CSV_AUSTIN,
    REPORTED_AT_CSV_AUSTIN,
    REPORTED_AT2_CSV_AUSTIN,

    /* dallas 311 */
    LATITUDE_311_DALLAS,
    LONGITUDE_311_DALLAS,
    LATITUDE_CSV_311_DALLAS,
    LONGITUDE_CSV_311_DALLAS,
    REPORTED_AT_CSV_311_DALLAS,

    /* dallas crime */
    LATITUDE_CSV_CRIME_DALLAS,
    LONGITUDE_CSV_CRIME_DALLAS,
    REPORTEDAT_CRIME_DALLAS,
    REPORTEDAT2_CRIME_DALLAS,
    REPORTEDAT_CSV_CRIME_DALLAS,
    REPORTEDAT2_CSV_CRIME_DALLAS,

    /* new york city */
    REPORTEDAT_CRIME_NEWYORKCITY,
    CREATED_DATE_311_NEWYORKCITY,

    /* boston */
    REPORTEDAT_BOSTON,
    REPORTEDAT_BOSTON_TIMEZONE_OFFSET
}
